- name: Bring down cockpit and qemu-kvm
  hosts: servers
  become: true

  tasks:
    - name: Stop and disable cockpit
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: false
        state: stopped

    - name: Stop and disable libvirtd
      ansible.builtin.systemd:
        name: libvirtd
        enabled: false
        state: stopped

    - name: Disable cockpit firewall service
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        immediate: true
        state: disabled

    - name: Remove qemu-kvm and cockpit packages
      ansible.builtin.dnf:
        name:
          - qemu-kvm
          - libvirt
          - libvirt-daemon-config-network
          - virt-install
          - cockpit
          - cockpit-machines
        state: absent
