- ansible.builtin.import_playbook: servers/netbootxyz/down.yaml
- ansible.builtin.import_playbook: servers/forgejo/down.yaml
- ansible.builtin.import_playbook: servers/nginx/down.yaml
- ansible.builtin.import_playbook: servers/cockpit/down.yaml
- ansible.builtin.import_playbook: servers/backup/down.yaml
- ansible.builtin.import_playbook: servers/network/down.yaml
- ansible.builtin.import_playbook: steamos/down.yaml
