- ansible.builtin.import_playbook: servers/network/up.yaml
- ansible.builtin.import_playbook: servers/backup/up.yaml
- ansible.builtin.import_playbook: servers/cockpit/up.yaml
- ansible.builtin.import_playbook: servers/nginx/up.yaml
- ansible.builtin.import_playbook: servers/forgejo/up.yaml
- ansible.builtin.import_playbook: servers/netbootxyz/up.yaml
- ansible.builtin.import_playbook: steamos/up.yaml
