- ansible.builtin.import_playbook: network/up.yaml
- ansible.builtin.import_playbook: backup/up.yaml
- ansible.builtin.import_playbook: cockpit/up.yaml
- ansible.builtin.import_playbook: nginx/up.yaml
- ansible.builtin.import_playbook: forgejo/up.yaml
- ansible.builtin.import_playbook: netbootxyz/up.yaml
- ansible.builtin.import_playbook: gluetun/up.yaml
- ansible.builtin.import_playbook: steamos/up.yaml
