- name: Bring down homelab network
  hosts: servers

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Remove port forwards
      ansible.posix.firewalld:
        port_forward:
          - port: "{{ item.port }}"
            proto: "{{ item.proto }}"
            toport: "{{ item.toport }}"
        permanent: true
        immediate: true
        state: disabled
      loop:
        - { port: "80",  proto: tcp, toport: "8080" }
        - { port: "443", proto: tcp, toport: "8443" }
      become: true
      when:
        - ansible_facts['services']['firewalld.service'] is defined
        - ansible_facts['services']['firewalld.service']['state'] == 'running'

    - name: Bring down network quadlet
      ansible.builtin.import_tasks: ../../common/tasks.down.yaml
