- name: Bring up homelab network
  hosts: servers

  tasks:
    - name: Bring up network
      ansible.builtin.import_tasks: ../../common/tasks.up.yaml
      vars:
        fw_forward_ports:
          - { port: "80",  proto: tcp, toport: "8080" }
          - { port: "443", proto: tcp, toport: "8443" }
          - { port: "69",  proto: udp, toport: "8069" }
