- name: Bring down netbootxyz
  hosts: servers

  vars:
    tftp_volume_path: "{{ ansible_facts['env']['HOME'] }}/.local/share/containers/storage/volumes/netbootxyz-assets/_data"

  tasks:
    - name: Stop and disable tftp.socket
      become: true
      ansible.builtin.systemd:
        name: tftp.socket
        enabled: false
        state: stopped
      ignore_errors: true

    - name: Stop tftp.service
      become: true
      ansible.builtin.systemd:
        name: tftp.service
        state: stopped
      ignore_errors: true

    - name: Remove tftp.service override
      become: true
      ansible.builtin.file:
        path: /etc/systemd/system/tftp.service.d
        state: absent

    - name: Remove SELinux file context for TFTP volume path
      become: true
      community.general.sefcontext:
        target: "{{ tftp_volume_path }}(/.*)?"
        setype: tftpdir_rw_t
        state: absent
      ignore_errors: true

    - name: Bring down service
      ansible.builtin.import_tasks: ../../common/tasks.down.yaml
      vars:
        systemd_services:
          - netbootxyz.service
