- name: Bring down forgejo
  hosts: servers

  tasks:
    - name: Bring down service
      ansible.builtin.import_tasks: ../../common/tasks.down.yaml
      vars:
        systemd_services:
          - forgejo.service
