- name: Bring up nginx
  hosts: servers

  tasks:
    - name: Bring up service
      ansible.builtin.import_tasks: ../common/tasks.up.yaml
      vars:
        fw_services:
          to_create:
            - name: nginx
              ports:
                - 8080/tcp
                - 8081/tcp
                - 8443/tcp
          to_enable:
            - nginx
        systemd_services:
          - nginx.service
