- name: Bring down steamos workstation
  hosts: steamos

  tasks:
    - name: Remove wireplumber config
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.config/wireplumber/wireplumber.conf.d/disable-suspension.conf"
        state: absent
