- name: Bring up steamos workstation
  hosts: steamos

  tasks:
    - name: Create wireplumber config directory
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/wireplumber/wireplumber.conf.d"
        state: directory
        mode: "0755"

    - name: Copy wireplumber config
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/wireplumber/disable-suspension.conf"
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/wireplumber/wireplumber.conf.d/disable-suspension.conf"
        mode: "0644"
